DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS file_types;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(20),
  
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role_id INT NOT NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_roles FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

/*
CREATE TABLE file_types (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(10),
  
  crated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;
*/

CREATE TABLE files (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(100),
  original_name VARCHAR(50),
  file_type enum('jpg', 'jpeg', 'png', 'docx', 'xlsx', 'csv'),
  user_id INT NOT NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  -- CONSTRAINT fk_types FOREIGN KEY (file_type_id) REFERENCES file_types(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

INSERT INTO `roles` VALUES (1,'admin','2021-10-15 21:41:15','2021-10-15 21:41:15'),(2,'user','2021-10-15 21:41:15','2021-10-15 21:41:15');
INSERT INTO `users` VALUES (4,'admin','admin@mycloud.com','$2b$10$EWUyT8hXU/nRY8UtSvznVedEnzvDyniO3OluomrgUB4roz5UVhATG',1,'2021-10-15 22:10:17','2021-10-15 22:10:17'),(5,'regular user 1','regular1@mycloud.com','$2b$10$vr9wQJBy70nb9CZUpM4OJOsWtLNCJfZ7LHAgI26xIuv14xWar1..G',2,'2021-10-15 22:36:19','2021-10-15 22:36:19'),(6,'regular user 2','regular2@mycloud.com','$2b$10$p61jHKqIScNd9LipVqFck.xD/FRE28lhfI7Y74QlhJ7is33BJlMUq',2,'2021-10-15 22:36:33','2021-10-15 22:36:33');
